// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Messenger$Type } from "./Messenger";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Messenger"]: Messenger$Type;
    ["contracts/Messenger.sol:Messenger"]: Messenger$Type;
  }
}
